/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "template.h"

bool_t
xdr_Output (XDR *xdrs, Output *objp)
{
	register int32_t *buf;

	 if (!xdr_String (xdrs, &objp->output))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Input (XDR *xdrs, Input *objp)
{
	register int32_t *buf;

	 if (!xdr_String (xdrs, &objp->input))
		 return FALSE;
	return TRUE;
}
