/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEMPLATE_H_RPCGEN
#define _TEMPLATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Output {
	String output;
};
typedef struct Output Output;

struct Input {
	String input;
};
typedef struct Input Input;

#define TEMPLATE 0x20000013
#define TEMPLATEVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define FUNZIONE_1 1
extern  void * funzione_1_1(void *, CLIENT *);
extern  void * funzione_1_1_svc(void *, struct svc_req *);
extern  void * funzione_1_1(void *, CLIENT *);
extern  void * funzione_1_1_svc(void *, struct svc_req *);
extern int template_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FUNZIONE_1 1
extern  void * funzione_1_1();
extern  void * funzione_1_1_svc();
extern  void * funzione_1_1();
extern  void * funzione_1_1_svc();
extern int template_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Output (XDR *, Output*);
extern  bool_t xdr_Input (XDR *, Input*);

#else /* K&R C */
extern bool_t xdr_Output ();
extern bool_t xdr_Input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEMPLATE_H_RPCGEN */
